<?php

// -----------------------------------------
// semplice
// admin/atts/customize/cursor.php
// -----------------------------------------

$cursor = array(
	'cursor-visibility' => array(
		'title'	 		=> 'Custom Cursor',
		'description' 	=> 'If enabled the normal cursor of the user will get replaced by a javascript cursor similar to the iPad. (when used with a trackpad)',
		'custom_cursor' => array(
			'data-input-type' 	=> 'switch',
			'switch-type'		=> 'twoway',
			'title'				=> 'Custom Cursor Usage',
			'hide-title'		=> true,
			'size'				=> 'span4',
			'class'				=> 'admin-listen-handler',
			'data-handler'  	=> 'advanced',
			'default' 	 		=> 'disabled',
			'switch-values' => array(
				'enabled'	 => 'Enabled',
				'disabled' 	 => 'Disabled',
			),
		),
	),
	'cursor-basic-colors' => array(
		'title'	 		=> 'Basic Cursor Customization',
		'description' 	=> 'Define the basic settings for your cursor in normal and mouseover status.',
		'break'			=> '1,3,1,4',
		'settings-title-0' => array(
			'data-input-type' 	=> 'settings-title',
			'switch-type'		=> 'twoway',
			'title'				=> 'settings-title',
			'hide-title'		=> true,
			'size'				=> 'span4',
			'default' 	 		=> 'Default Cursor',
			'style-class'		=> 'settings-title settings-title-top',
		),
		'color' => array(
			'title'			=> 'Color',
			'size'			=> 'span1',
			'data-input-type'	=> 'color',
			'default'		=> '#666666',
			'class'			=> 'color-picker admin-listen-handler',
			'data-handler'  => 'colorPicker',
			'data-picker'	=> 'advanced',
		),
		'size' => array(
			'title'				=> 'Size (in px)',
			'size'				=> 'span1',
			'offset'			=> false,
			'data-input-type' 	=> 'range-slider',
			'class'				=> 'admin-listen-handler',
			'data-handler'		=> 'advanced',
			'default'			=> 14,
			'min'				=> 0,
			'max'				=> 999,
			'data-range-slider' => 'advanced',
		),
		'blend_mode' => array(
			'title'				=> 'Blend Mode',
			'size'				=> 'span1',
			'data-input-type'	=> 'select-box',
			'class'				=> 'admin-listen-handler',
			'data-handler'  	=> 'advanced',
			'default'			=> 'normal',
			'select-box-values' => $atts->blend_modes,
		),
		'settings-title-1' => array(
			'data-input-type' 	=> 'settings-title',
			'switch-type'		=> 'twoway',
			'title'				=> 'settings-title',
			'hide-title'		=> true,
			'size'				=> 'span4',
			'default' 	 		=> 'Mouseover Cursor',
			'style-class'		=> 'settings-title',
		),
		'mouseover_color' => array(
			'title'			=> 'Color',
			'size'			=> 'span1',
			'data-input-type'	=> 'color',
			'default'		=> '#000000',
			'class'			=> 'color-picker admin-listen-handler',
			'data-handler'  => 'colorPicker',
			'data-picker'	=> 'advanced',
		),
		'mouseover_size' => array(
			'title'				=> 'Size (in px)',
			'size'				=> 'span1',
			'offset'			=> false,
			'data-input-type' 	=> 'range-slider',
			'class'				=> 'admin-listen-handler',
			'data-handler'		=> 'advanced',
			'default'			=> 64,
			'min'				=> 0,
			'max'				=> 999,
			'data-range-slider' => 'advanced',
		),
		'mouseover_blend_mode' => array(
			'title'				=> 'Blend Mode',
			'size'				=> 'span1',
			'data-input-type'	=> 'select-box',
			'class'				=> 'admin-listen-handler',
			'data-handler'  	=> 'advanced',
			'default'			=> 'normal',
			'select-box-values' => $atts->blend_modes,
		),
		'inner_color' => array(
			'title'			=> 'Text/Icon Color',
			'size'			=> 'span1',
			'data-input-type'	=> 'color',
			'default'		=> '#ffffff',
			'class'			=> 'color-picker admin-listen-handler',
			'data-handler'  => 'colorPicker',
			'data-picker'	=> 'advanced',
		),
	),
	'cursor-cases' => $atts->get('cursor', false),
);