<?php

// -----------------------------------------
// semplice
// admin/atts/partials/mobile/apg.php
// -----------------------------------------

// names
$title = array(
	'lg' => 'Desktop Options',
	'md' => 'Tablet Landscape Options',
	'sm' => 'Tablet Portrait Options',
	'xs' => 'Mobile Options',
);
// define mobile options
if($args['grid'] == 'hor-full') {

	// default width
	$default_width = array('lg' => 6, 'md' => 6, 'sm' => 12, 'xs' => 12);

	$options = array(
		'title'  	 => $title[$breakpoint],
		'break'		 => '2,2,2,2,1',
		'class'		 => 'mobile-option mobile-option-' .$breakpoint,
		'style-class'=> 'apg-responsive-horfull-' . $breakpoint,
		'hor_full_width_' . $breakpoint => array(
			'data-input-type' => 'select-box',
			'title'		 => 'Images per Row',
			'size'		 => 'span2',
			'class'      	=> 'editor-listen',
			'data-handler' 	=> 'apg',
			'default' 	 => $default_width[$breakpoint],
			'responsive'	=> true,
			'responsive-default' => true,
			'select-box-values' => array(
				'12' => '1 Image',
				'6' => '2 Images',
				'4' => '3 Images',
				'3' => '4 Images',
			),
		),
		'hor_full_arrow_size_' . $breakpoint => array(
			'data-input-type' => 'select-box',
			'title'		 => 'Arrow Size',
			'size'		 => 'span2',
			'class'      	=> 'editor-listen',
			'data-handler' 	=> 'apg',
			'default' 	 => 'small',
			'responsive'	=> true,
			'data-responsive-option' => 'apg',
			'select-box-values' => array(
				'small' 		=> 'Small',
				'medium' 		=> 'Medium',
				'large' 		=> 'Large',
				'insane' 		=> 'Insane',
			),
		),
		'hor_full_title_padding_' . $breakpoint => array(
			'title'			=> 'Title Padding',
			'size'			=> 'span2',
			'offset'		=> false,
			'data-input-type' => 'range-slider',
			'default'		=> 72,
			'min'			=> 0,
			'max'			=> 999,
			'class'				=> 'editor-listen',
			'data-handler'		=> 'apg',
			'data-range-slider' => 'apg',
			'data-style-option' => true,
			'data-has-unit'	=> true,
			'data-css-attribute'=> 'padding',
			'responsive'	=> true,
			'data-responsive-option' => 'apg',
		),
		'hor_full_title_offset_' . $breakpoint => array(
			'title'			=> 'Title Offset',
			'size'			=> 'span2',
			'offset'		=> false,
			'data-input-type' => 'range-slider',
			'default'		=> 0,
			'min'			=> 0,
			'max'			=> 999,
			'class'				=> 'editor-listen',
			'data-handler'		=> 'apg',
			'data-range-slider' => 'apg',
			'data-style-option' => true,
			'data-has-unit'	=> true,
			'help'			=> 'Define the vertical offset of your title. This is an addition to the padding because sometimes you want a small horizontal padding but at the same time you dont want your title to stick to the top or bottom edge.',
			'responsive'	=> true,
			'data-responsive-option' => 'apg',
		),
		'hor_full_title_fontsize_' . $breakpoint => array(
			'title'			=> 'Title Font Size',
			'size'			=> 'span2',
			'offset'		=> false,
			'data-input-type' 	=> 'range-slider',
			'default'		=> 42,
			'min'			=> 0,
			'max'			=> 999,
			'class'				=> 'editor-listen',
			'data-handler'		=> 'apg',
			'data-style-option' => true,
			'data-has-unit'	=> true,
			'data-css-attribute'=> 'font-size',
			'data-range-slider' => 'apg',
			'responsive'	=> true,
			'data-responsive-option' => 'apg',
		),
		'hor_full_title_letter_spacing_' . $breakpoint => array(
			'title'				=> 'Letter Spacing',
			'size'				=> 'span2',
			'data-input-type' 	=> 'range-slider',
			'data-css-attribute'=> 'letter-spacing',
			'data-style-option' => true,
			'data-has-unit'		=> true,
			'default'			=> 0,
			'min'				=> 0,
			'max'				=> 9999,
			'data-negative' 	=> true,
			'data-divider'		=> 10,
			'class' 	 		=> 'editor-listen',
			'data-handler'		=> 'apg',
			'data-range-slider' => 'apg',
			'responsive'	=> true,
			'data-responsive-option' => 'apg',
		),
		'hor_full_title_line_height_' . $breakpoint => array(
			'title'				=> 'Line Height',
			'size'				=> 'span2',
			'data-input-type' 	=> 'range-slider',
			'default'			=> 100,
			'min'				=> 0,
			'max'				=> 9999,
			'class' 	 		=> 'editor-listen',
			'data-handler'		=> 'apg',
			'data-range-slider' => 'apg',
			'responsive'	=> true,
			'data-responsive-option' => 'apg',
		),
		'hor_full_type_fontsize_' . $breakpoint => array(
			'title'			=> 'Type Font Size',
			'size'			=> 'span2',
			'offset'		=> false,
			'data-input-type' 	=> 'range-slider',
			'default'		=> 20,
			'min'			=> 0,
			'max'			=> 999,
			'class'				=> 'editor-listen',
			'data-handler'		=> 'apg',
			'data-style-option' => true,
			'data-has-unit'		=> true,
			'data-css-attribute'=> 'font-size',
			'data-range-slider' => 'apg',
			'responsive'	=> true,
			'data-responsive-option' => 'apg',
		),
		'hor_full_type_padding_top_' . $breakpoint => array(
			'title'			=> 'Padding Top',
			'size'			=> 'span2',
			'offset'		=> false,
			'data-input-type' => 'range-slider',
			'default'		=> 10,
			'min'			=> 0,
			'max'			=> 999,
			'class'				=> 'editor-listen',
			'data-handler'		=> 'apg',
			'data-range-slider' => 'apg',
			'data-style-option' => true,
			'data-has-unit'	=> true,
			'data-css-attribute'=> 'padding-top',
			'responsive'	=> true,
			'data-responsive-option' => 'apg',
		),
	);
} else if($args['grid'] == 'text') {
	$options = array(
		'title'  	 => $title[$breakpoint],
		'break'		 => '2,2,2',
		'class'		 => 'mobile-option mobile-option-' .$breakpoint,
		'style-class'	=> 'apg-responsive-text-' . $breakpoint,
		'text_title_padding_' . $breakpoint => array(
			'title'			=> 'Outer Padding',
			'help'			=> 'This setting has no effect if title position is set to \'Middle Center\'.',
			'size'			=> 'span2',
			'offset'		=> false,
			'data-input-type' => 'range-slider',
			'default'		=> 72,
			'min'			=> 0,
			'max'			=> 999,
			'class'				=> 'editor-listen',
			'data-handler'		=> 'apg',
			'data-range-slider' => 'apg',
			'data-style-option' => true,
			'data-has-unit'	=> true,
			'data-css-attribute'=> 'padding',
			'data-responsive-option' => 'apg',
			'responsive'	=> true,
		),
		'text_title_item_padding_ver_' . $breakpoint => array(
			'title'			=> 'Item Padding Vert',
			'size'			=> 'span2',
			'offset'		=> false,
			'data-input-type' => 'range-slider',
			'default'		=> 10,
			'min'			=> 0,
			'max'			=> 999,
			'class'				=> 'editor-listen',
			'data-handler'		=> 'apg',
			'data-range-slider' => 'apg',
			'data-style-option' => true,
			'data-has-unit'	=> true,
			'data-responsive-option' => 'apg',
			'responsive'	=> true,
		),
		'text_title_item_padding_hor_' . $breakpoint => array(
			'title'			=> 'Item Padding Hor',
			'size'			=> 'span2',
			'offset'		=> false,
			'data-input-type' => 'range-slider',
			'default'		=> 18,
			'min'			=> 0,
			'max'			=> 999,
			'class'				=> 'editor-listen',
			'data-handler'		=> 'apg',
			'data-range-slider' => 'apg',
			'data-style-option' => true,
			'data-has-unit'	=> true,
			'data-responsive-option' => 'apg',
			'responsive'	=> true,
		),
		'text_title_fontsize_' . $breakpoint => array(
			'title'			=> 'Font Size',
			'size'			=> 'span2',
			'offset'		=> false,
			'data-input-type' 	=> 'range-slider',
			'default'		=> 90,
			'min'			=> 0,
			'max'			=> 999,
			'class'				=> 'editor-listen',
			'data-handler'		=> 'apg',
			'data-style-option' => true,
			'data-has-unit'	=> true,
			'data-css-attribute'=> 'font-size',
			'data-range-slider' => 'apg',
			'responsive'	=> true,
			'data-responsive-option' => 'apg',
		),
		'text_title_line_height_' . $breakpoint => array(
			'title'				=> 'Line Height',
			'size'				=> 'span2',
			'data-input-type' 	=> 'range-slider',
			'default'			=> 100,
			'min'				=> 0,
			'max'				=> 9999,
			'class' 	 		=> 'editor-listen',
			'data-handler'		=> 'apg',
			'data-range-slider' => 'apg',
			'responsive'	=> true,
			'data-responsive-option' => 'apg',
		),
		'text_title_letter_spacing_' . $breakpoint => array(
			'title'				=> 'Letter Spacing',
			'size'				=> 'span2',
			'data-input-type' 	=> 'range-slider',
			'data-css-attribute'=> 'letter-spacing',
			'data-style-option' => true,
			'data-has-unit'		=> true,
			'default'			=> 0,
			'min'				=> 0,
			'max'				=> 9999,
			'data-negative' 	=> true,
			'data-divider'		=> 10,
			'class' 	 		=> 'editor-listen',
			'data-handler'		=> 'apg',
			'data-range-slider' => 'apg',
			'responsive'	=> true,
			'data-responsive-option' => 'apg',
		),
	);
} else if($args['grid'] == 'splitscreen') {

	// default width
	$default_width = array('lg' => 6, 'md' => 6, 'sm' => 12, 'xs' => 12);

	$options = array(
		'title'  	 => $title[$breakpoint],
		'break'		 => '2,2,2,2,2,2,1',
		'class'		 => 'mobile-option mobile-option-' .$breakpoint,
		'style-class'=> 'apg-responsive-splitscreen-' . $breakpoint,
		'splitscreen_title_padding_' . $breakpoint => array(
			'title'			=> 'Title Padding',
			'size'			=> 'span2',
			'offset'		=> false,
			'data-input-type' => 'range-slider',
			'default'		=> 72,
			'min'			=> 0,
			'max'			=> 999,
			'class'				=> 'editor-listen',
			'data-handler'		=> 'apg',
			'data-range-slider' => 'apg',
			'data-style-option' => true,
			'data-has-unit'	=> true,
			'data-css-attribute'=> 'padding',
			'responsive'	=> true,
			'data-responsive-option' => 'apg',
		),
		'splitscreen_title_offset_' . $breakpoint => array(
			'title'			=> 'Title Offset',
			'size'			=> 'span2',
			'offset'		=> false,
			'data-input-type' => 'range-slider',
			'default'		=> 0,
			'min'			=> 0,
			'max'			=> 999,
			'class'				=> 'editor-listen',
			'data-handler'		=> 'apg',
			'data-range-slider' => 'apg',
			'data-style-option' => true,
			'data-has-unit'	=> true,
			'help'			=> 'Define the vertical offset of your title. This is an addition to the padding because sometimes you want a small horizontal padding but at the same time you dont want your title to stick to the top or bottom edge.',
			'responsive'	=> true,
			'data-responsive-option' => 'apg',
		),
		'splitscreen_title_fontsize_' . $breakpoint => array(
			'title'			=> 'Title Font Size',
			'size'			=> 'span2',
			'offset'		=> false,
			'data-input-type' 	=> 'range-slider',
			'default'		=> 42,
			'min'			=> 0,
			'max'			=> 999,
			'class'				=> 'editor-listen',
			'data-handler'		=> 'apg',
			'data-style-option' => true,
			'data-has-unit'	=> true,
			'data-css-attribute'=> 'font-size',
			'data-range-slider' => 'apg',
			'responsive'	=> true,
			'data-responsive-option' => 'apg',
		),
		'splitscreen_title_letter_spacing_' . $breakpoint => array(
			'title'				=> 'Title Letter Spacing',
			'size'				=> 'span2',
			'data-input-type' 	=> 'range-slider',
			'data-css-attribute'=> 'letter-spacing',
			'data-style-option' => true,
			'data-has-unit'		=> true,
			'default'			=> 0,
			'min'				=> 0,
			'max'				=> 9999,
			'data-negative' 	=> true,
			'data-divider'		=> 10,
			'class' 	 		=> 'editor-listen',
			'data-handler'		=> 'apg',
			'data-range-slider' => 'apg',
			'responsive'	=> true,
			'data-responsive-option' => 'apg',
		),
		'splitscreen_title_line_height_' . $breakpoint => array(
			'title'				=> 'Title Line Height',
			'size'				=> 'span2',
			'data-input-type' 	=> 'range-slider',
			'default'			=> 100,
			'min'				=> 0,
			'max'				=> 9999,
			'class' 	 		=> 'editor-listen',
			'data-handler'		=> 'apg',
			'data-range-slider' => 'apg',
			'responsive'	=> true,
			'data-responsive-option' => 'apg',
		),
		'splitscreen_type_fontsize_' . $breakpoint => array(
			'title'			=> 'Desc Font Size',
			'size'			=> 'span2',
			'offset'		=> false,
			'data-input-type' 	=> 'range-slider',
			'default'		=> 20,
			'min'			=> 0,
			'max'			=> 999,
			'class'				=> 'editor-listen',
			'data-handler'		=> 'apg',
			'data-style-option' => true,
			'data-has-unit'		=> true,
			'data-css-attribute'=> 'font-size',
			'data-range-slider' => 'apg',
			'responsive'	=> true,
			'data-responsive-option' => 'apg',
		),
		'splitscreen_type_padding_top_' . $breakpoint => array(
			'title'			=> 'Desc Padding Top',
			'size'			=> 'span2',
			'offset'		=> false,
			'data-input-type' => 'range-slider',
			'default'		=> 10,
			'min'			=> 0,
			'max'			=> 999,
			'class'				=> 'editor-listen',
			'data-handler'		=> 'apg',
			'data-range-slider' => 'apg',
			'data-style-option' => true,
			'data-has-unit'	=> true,
			'data-css-attribute'=> 'padding-top',
			'responsive'	=> true,
			'data-responsive-option' => 'apg',
		),
		'splitscreen_details_padding_top_' . $breakpoint  => array(
			'title'			=> 'Button Top Spacing',
			'size'			=> 'span2',
			'offset'		=> false,
			'data-input-type' => 'range-slider',
			'default'		=> 36,
			'min'			=> 0,
			'max'			=> 999,
			'class'				=> 'editor-listen',
			'data-handler'		=> 'apg',
			'data-range-slider' => 'apg',
			'data-style-option' => true,
			'data-has-unit'	=> true,
			'data-css-attribute'=> 'margin-top',
			'data-target'		=> '.apg-post-title .details',
			'responsive'	=> true,
			'data-responsive-option' => 'apg',
		),
		'splitscreen_details_padding_ver_' . $breakpoint  => array(
			'title'			=> 'Button Spacing Ver',
			'size'			=> 'span2',
			'offset'		=> false,
			'data-input-type' 	=> 'range-slider',
			'default'		=> 14,
			'min'			=> 0,
			'max'			=> 999,
			'class'				=> 'editor-listen',
			'data-handler'		=> 'apg',
			'data-target'		=> '.apg-post-title .details a',
			'data-has-unit'		=> true,
			'data-range-slider' => 'apg',
			'responsive'	=> true,
			'data-responsive-option' => 'apg',
		),
		'splitscreen_details_padding_hor_' . $breakpoint  => array(
			'title'			=> 'Button Spacing Hor',
			'size'			=> 'span2',
			'offset'		=> false,
			'data-input-type' 	=> 'range-slider',
			'default'		=> 14,
			'min'			=> 0,
			'max'			=> 999,
			'class'				=> 'editor-listen',
			'data-handler'		=> 'apg',
			'data-target'		=> '.apg-post-title .details a',
			'data-has-unit'		=> true,
			'data-range-slider' => 'apg',
			'responsive'	=> true,
			'data-responsive-option' => 'apg',
		),
		'splitscreen_details_border_' . $breakpoint  => array(
			'title'			=> 'Button Border',
			'size'			=> 'span2',
			'offset'		=> false,
			'data-input-type' 	=> 'range-slider',
			'default'		=> 1,
			'min'			=> 0,
			'max'			=> 999,
			'class'				=> 'editor-listen',
			'data-handler'		=> 'apg',
			'data-target'		=> '.apg-post-title .details a',
			'data-has-unit'		=> true,
			'data-range-slider' => 'apg',
			'responsive'	=> true,
			'data-responsive-option' => 'apg',
		),
		'splitscreen_details_fontsize_' . $breakpoint  => array(
			'title'			=> 'Button Font Size',
			'size'			=> 'span2',
			'offset'		=> false,
			'data-input-type' 	=> 'range-slider',
			'default'		=> 20,
			'min'			=> 0,
			'max'			=> 999,
			'class'				=> 'editor-listen',
			'data-handler'		=> 'apg',
			'data-target'		=> '.apg-post-title .details a',
			'data-style-option' => true,
			'data-has-unit'		=> true,
			'data-css-attribute'=> 'font-size',
			'data-range-slider' => 'apg',
			'responsive'	=> true,
			'data-responsive-option' => 'apg',
		),
		'splitscreen_details_letter_spacing_' . $breakpoint  => array(
			'title'				=> 'Btn Letter Spacing',
			'size'				=> 'span2',
			'data-input-type' 	=> 'range-slider',
			'data-css-attribute'=> 'letter-spacing',
			'data-style-option' => true,
			'data-target'		=> '.apg-post-title .details a',
			'default'			=> 0,
			'min'				=> 0,
			'max'				=> 9999,
			'data-negative' 	=> true,
			'data-has-unit'		=> true,
			'data-divider'		=> 10,
			'class' 	 		=> 'editor-listen',
			'data-handler'		=> 'apg',
			'data-range-slider' => 'apg',
			'responsive'	=> true,
			'data-responsive-option' => 'apg',
		),
	);
} else if($args['grid'] == 'table') {
	if($args['type'] == 'layout') {
		$options = array(
			'title'  	 		=> 'Layout Options',
			'break'		 		=> '1',
			'style-class'		=> 'ov-apg-table',
			'class'		 		=> 'mobile-option mobile-option-' .$breakpoint,
			'style-class'		=> 'apg-responsive-table-' . $breakpoint,
			'table_padding_hor_' . $breakpoint => array(
				'title'				=> 'Text Indent',
				'size'				=> 'span2',
				'offset'			=> false,
				'data-input-type' 	=> 'range-slider',
				'default'			=> 30,
				'min'				=> 0,
				'max'				=> 999,
				'class'     		=> 'editor-listen',
				'data-handler'  	=> 'apg',
				'data-has-unit'		=> true,
				'responsive'		=> true,
				'data-range-slider' => 'apg',
				'data-responsive-option' => 'apg',
			),
		);
	} else if($args['type'] == 'head-formatting') {
		$options = array(
			'title'  	 => 'Title Row',
			'break'		 => '2,1',
			'class'		 		=> 'mobile-option mobile-option-' .$breakpoint,
			'style-class'		=> 'ep-collapsed apg-responsive-table-' . $breakpoint,
			'table_head_padding_' . $breakpoint => array(
				'title'				=> 'Padding',
				'size'				=> 'span2',
				'offset'			=> false,
				'data-input-type' 	=> 'range-slider',
				'default'			=> 16,
				'min'				=> 0,
				'max'				=> 999,
				'class'     		=> 'editor-listen',
				'data-handler'  	=> 'apg',
				'data-target'		=> '.apg-table-head',
				'data-has-unit'		=> true,
				'data-range-slider' => 'apg',
				'data-responsive-option' => 'apg',
				'responsive'		=> true,
			),
			'table_head_font_size_' . $breakpoint => array(
				'data-css-attribute' => 'font-size',
				'title'			=> 'Font Size',
				'size'			=> 'span2',
				'offset'		=> false,
				'data-input-type' 	=> 'range-slider',
				'default'		=> 13,
				'min'			=> 6,
				'max'			=> 999,
				'class'     	=> 'editor-listen',
				'data-handler'  => 'apg',
				'data-target'		=> '.apg-table-head',
				'data-has-unit'	=> true,
				'data-range-slider' => 'apg',
				'data-responsive-option' => 'apg',
				'responsive'		=> true,
			),
			'table_head_letter_spacing_' . $breakpoint => array(
				'data-css-attribute' => 'letter-spacing',
				'title'				=> 'Letter Spacing',
				'size'				=> 'span2',
				'data-input-type' 	=> 'range-slider',
				'default'			=> 0,
				'min'				=> 0,
				'max'				=> 9999,
				'data-negative' 	=> true,
				'data-has-unit'		=> true,
				'data-divider'		=> 10,
				'class' 	 		=> 'editor-listen',
				'data-handler'		=> 'apg',
				'data-range-slider' => 'apg',
				'data-target'		=> '.apg-table-head',
				'data-responsive-option' => 'apg',
				'responsive'		=> true,
			),
		);
	} else if($args['type'] == 'column-options') {
		$options = array(
			'title'  	 => 'Seperator &amp; Row Spacing',
			'break'		 => '2',
			'class'		 		=> 'mobile-option mobile-option-' .$breakpoint,
			'style-class'		=> 'ep-collapsed apg-responsive-table-' . $breakpoint,
			'table_seperator_width_' . $breakpoint => array(
				'data-css-attribute' => 'border-top-width',
				'title'			=> 'Seperator Width',
				'size'			=> 'span2',
				'offset'		=> false,
				'data-input-type' 	=> 'range-slider',
				'default'		=> 1,
				'min'			=> 0,
				'max'			=> 999,
				'class'     	=> 'editor-listen',
				'data-handler'  => 'apg',
				'data-has-unit'	=> true,
				'data-range-slider' => 'apg',
				'data-target'=> '.apg-table-link',
				'data-responsive-option' => 'apg',
				'responsive'		=> true,
			),
			'table_padding_' . $breakpoint => array(
				'title'				=> 'Vertical Spacing',
				'size'				=> 'span2',
				'offset'			=> false,
				'data-input-type' 	=> 'range-slider',
				'default'			=> 16,
				'min'				=> 0,
				'max'				=> 999,
				'class'     		=> 'editor-listen',
				'data-handler'  	=> 'apg',
				'data-target'		=> '.apg-table-head',
				'data-has-unit'		=> true,
				'data-range-slider' => 'apg',
				'data-responsive-option' => 'apg',
				'responsive'		=> true,
			),
		);
	}
}