<?php

// -----------------------------------------
// semplice
// admin/atts/partials/mobile/blogarchive.php
// -----------------------------------------

$options = array(
	'title'  	 => $title . ' Options',
	'break'		 => '2,2,2,1',
	'class'		 => 'mobile-option mobile-option-' .$breakpoint,
	'align_' . $breakpoint => array(
		'data-input-type' => 'select-box',
		'title'		 => 'Align',
		'size'		 => 'span2',
		'class'			=> 'editor-listen',
		'data-handler'	=> 'blogarchives',
		'default' 	 => 'left',
		'responsive' => true,
		'select-box-values' => array(
			'left'			=> 'Left',
			'center'		=> 'Center',
			'right'			=> 'Right',
		),
	),
	'font_size_' . $breakpoint => array(
		'title'			=> 'Font Size',
		'size'			=> 'span2',
		'offset'		=> false,
		'data-input-type' 	=> 'range-slider',
		'default'		=> 18,
		'min'			=> 6,
		'max'			=> 999,
		'class'     	=> 'editor-listen',
		'data-handler'  => 'blogarchives',
		'data-range-slider' => 'blogarchives',
		'data-has-unit'	=> true,
		'responsive' => true,
	),
	'line_height_' . $breakpoint => array(
		'title'			=> 'Line Height',
		'size'			=> 'span2',
		'offset'		=> false,
		'data-input-type' 	=> 'range-slider',
		'default'		=> 26,
		'min'			=> 0,
		'max'			=> 999,
		'class'     	=> 'editor-listen',
		'data-handler'  => 'blogarchives',
		'data-range-slider' => 'blogarchives',
		'data-has-unit'	=> true,
		'responsive' => true,
	),
	'letter_spacing_' . $breakpoint => array(
		'title'				=> 'Letter Spacing',
		'size'				=> 'span2',
		'data-input-type' 	=> 'range-slider',
		'default'			=> 0,
		'min'				=> 0,
		'max'				=> 9999,
		'data-negative' 	=> true,
		'data-has-unit'		=> true,
		'data-divider'		=> 10,
		'class' 	 		=> 'editor-listen',
		'data-handler'		=> 'blogarchives',
		'data-range-slider' => 'blogarchives',
		'responsive' => true,
	),
	'padding_ver_' . $breakpoint => array(
		'title'			=> 'Padding Ver',
		'size'			=> 'span2',
		'offset'		=> false,
		'data-input-type' 	=> 'range-slider',
		'default'		=> 10,
		'min'			=> 0,
		'max'			=> 999,
		'class'     	=> 'editor-listen',
		'data-handler'  => 'blogarchives',
		'data-range-slider' => 'blogarchives',
		'data-has-unit'	=> true,
		'responsive' => true,
	),
	'padding_hor_' . $breakpoint => array(
		'title'			=> 'Padding Hor',
		'size'			=> 'span2',
		'offset'		=> false,
		'data-input-type' 	=> 'range-slider',
		'default'		=> 0,
		'min'			=> 0,
		'max'			=> 999,
		'class'     	=> 'editor-listen',
		'data-handler'  => 'blogarchives',
		'data-range-slider' => 'blogarchives',
		'data-has-unit'	=> true,
		'responsive' => true,
	),
	'seperator_height_' . $breakpoint => array(
		'title'			=> 'Seperator Height',
		'size'			=> 'span2',
		'offset'		=> false,
		'data-input-type' 	=> 'range-slider',
		'default'		=> 1,
		'min'			=> 0,
		'max'			=> 999,
		'class'     	=> 'editor-listen',
		'data-handler'  => 'blogarchives',
		'data-range-slider' => 'blogarchives',
		'data-has-unit'	=> true,
		'responsive' => true,
	),
);

?>