<?php

// -----------------------------------------
// semplice
// admin/atts/partials/mobile/marquee.php
// -----------------------------------------

$options = array(
	'title'  	 => $title . ' Options',
	'break'		 => '1,2,2,2',
	'class'		 => 'mobile-option mobile-option-' . $breakpoint,
	'speed_' . $breakpoint => array(
		'title'			=> 'Speed',
		'size'			=> 'span2',
		'offset'		=> false,
		'data-input-type' 	=> 'range-slider',
		'default'		=> 200,
		'min'			=> 0,
		'max'			=> 9999,
		'class'				=> 'editor-listen',
		'data-handler'		=> 'save',
		'responsive'	=> true,
	),
	'custom_width_' . $breakpoint => array(
		'title'			=> 'Custom Width (in %)',
		'size'			=> 'span2',
		'offset'		=> false,
		'data-input-type' 	=> 'range-slider',
		'default'		=> 100,
		'min'			=> 0,
		'max'			=> 100,
		'class'				=> 'editor-listen',
		'data-handler'		=> 'marquee',
		'data-range-slider' => 'marquee',
		'style-class'	=> 'ov-marquee-image',
		'responsive'	=> true,
		'help' 			=> 'This setting will only work if you set \'Image Width\' to \'Custom\' in the module settings for the \'Desktop Wide\' breakpoint.',
	),
	'margin_right_' . $breakpoint => array(
		'title'			=> 'Spacing (px)',
		'size'			=> 'span2',
		'offset'		=> false,
		'data-input-type' 	=> 'range-slider',
		'default'		=> 18,
		'min'			=> 0,
		'max'			=> 999,
		'class'				=> 'editor-listen',
		'data-handler'		=> 'marquee',
		'data-range-slider' => 'marquee',
		'data-has-unit'	=> true,
		'help' => 'Define your spacing for:<br /><br /><b>Text mode</b><br />The spacing will get added at the end of your text.<br /><br /><b>Image mode</b><br />Spacing will get added after each image.',
		'responsive'	=> true,
	),
	'fontsize_' . $breakpoint => array(
		'title'			=> 'Font Size',
		'size'			=> 'span2',
		'offset'		=> false,
		'data-input-type' 	=> 'range-slider',
		'default'		=> 54,
		'min'			=> 0,
		'max'			=> 999,
		'class'				=> 'editor-listen',
		'data-handler'		=> 'marquee',
		'data-has-unit'	=> true,
		'data-range-slider' => 'marquee',
		'responsive'	=> true,
	),
	'lineheight_' . $breakpoint => array(
		'title'			=> 'Line Height',
		'size'			=> 'span2',
		'offset'		=> false,
		'data-input-type' 	=> 'range-slider',
		'default'		=> 72,
		'min'			=> 0,
		'max'			=> 999,
		'class'				=> 'editor-listen',
		'data-handler'		=> 'marquee',
		'data-has-unit'	=> true,
		'data-range-slider' => 'marquee',
		'responsive'	=> true,
	),
	'letter_spacing_' . $breakpoint => array(
		'title'			=> 'Letter Spacing',
		'size'			=> 'span2',
		'offset'		=> false,
		'data-input-type' 	=> 'range-slider',
		'default'		=> 0,
		'min'			=> 0,
		'max'			=> 9999,
		'class'			=> 'editor-listen',
		'data-handler'	=> 'marquee',
		'data-divider'  => 10,
		'data-has-unit'	=> true,
		'data-negative' => true,
		'data-range-slider' => 'marquee',
		'help'			=> 'This value increments the letter spacing in 0.1px steps. <br /><br /><b>Example:</b> 10 = 1px. <br /><br /><b>Note:</b><br />You will see the letter spacing also added to the last char on the right while editing. For the frontend this will get compensated with a negative margin to correctly align your button label.',
		'responsive'	=> true,
	)
);

?>