<?php

// -----------------------------------------
// semplice
// admin/atts/partials/mobile/pgfilter.php
// -----------------------------------------

$options = array(
	'title'  	 => 'Category Filter',
	'break'		 => '1,2,2',
	'class'		 => 'mobile-option mobile-option-' .$breakpoint,
	'style-class'=> 'ep-collapsed',
	'filter_alignment_' . $breakpoint => array(
		'title'				=> 'Alignment',
		'size'				=> 'span4',
		'data-input-type'	=> 'select-box',
		'class'				=> 'editor-listen',
		'data-handler'		=> 'save',
		'default'			=> 'right',
		'responsive'		=> true,
		'select-box-values' => array(
			'left'			=> 'Left',
			'center'		=> 'Center',
			'right'			=> 'Right',
		),
	),
	'filter_padding_' . $breakpoint => array(
		'title'				=> 'Padding Bottom',
		'size'				=> 'span2',
		'offset'			=> false,
		'data-input-type' 	=> 'range-slider',
		'default'			=> 28,
		'min'				=> 0,
		'max'				=> 999,
		'class'				=> 'editor-listen',
		'data-handler'		=> 'save',
		'data-style-option' => true,
		'data-has-unit'	=> true,
		'responsive'	=> true,
	),
	'filter_item_padding_' . $breakpoint => array(
		'title'				=> 'Item Padding',
		'size'				=> 'span2',
		'offset'			=> false,
		'data-input-type' 	=> 'range-slider',
		'default'			=> 28,
		'min'				=> 0,
		'max'				=> 999,
		'class'				=> 'editor-listen',
		'data-handler'		=> 'save',
		'data-style-option' => true,
		'data-has-unit'	=> true,
		'responsive'	=> true,
	),
	'filter_fontsize_' . $breakpoint => array(
		'title'				=> 'Font Size',
		'size'				=> 'span2',
		'offset'			=> false,
		'data-input-type' 	=> 'range-slider',
		'default'			=> 20,
		'min'				=> 0,
		'max'				=> 999,
		'class'				=> 'editor-listen',
		'data-handler'		=> 'save',
		'data-style-option' => true,
		'data-has-unit'	=> true,
		'responsive'	=> true,
	),
	'filter_letter_spacing_' . $breakpoint => array(
		'title'				=> 'Letter Spacing',
		'size'				=> 'span2',
		'offset'			=> false,
		'data-input-type' 	=> 'range-slider',
		'default'			=> 0,
		'min'				=> 0,
		'max'				=> 9999,
		'class'				=> 'editor-listen',
		'data-handler'		=> 'save',
		'data-style-option' => true,
		'data-divider'  	=> 10,
		'data-has-unit'		=> true,
		'data-negative' 	=> true,
		'help'				=> 'This value increments the letter spacing in 0.1px steps. <br /><br /><b>Example:</b> 10 = 1px.',
		'responsive'		=> true,
	),
);