<?php

// -----------------------------------------
// semplice
// admin/atts/partials/blogcomments.php
// -----------------------------------------

$options = array(
	'comments-general' => array(
		'title' => 'General',
		'break'	=> '2',
		'style-class'	=> 'hide-for-bc-module',
		'comments_visibility' => array(
			'data-input-type' 			=> 'switch',
			'switch-type'				=> 'twoway',
			'title'		 				=> 'Visibility',
			'size'		 				=> 'span2',
			'class'						=> $args['handler'],
			'data-handler'				=> 'blog',
			'default' 	 				=> 'visible',
			'data-target'				=> '.admin-blog-container',
			'help'						=> 'If set to hidden, the entire comments section (including the comments linked above the title) will not be visible.',
			'switch-values' => array(
				'visible'	=> 'Visible',
				'hidden'  	=> 'Hidden',
			),
		),
		'comment_bg_color' => array(
			'title'			=> 'Background Color',
			'data-css-attribute' => 'background-color',
			'size'			=> 'span2',
			'data-input-type'	=> 'color',
			'data-target'	=> '#comments',
			'default'		=> 'transparent',
			'class'			=> 'color-picker admin-listen-handler',
			'data-handler'  => 'colorPicker',
			'data-has-unit'	=> false,
			'data-picker'   => 'blog',
		),
	),
	'title-options' => array(
		'title' => 'Title',
		'break'	=> '1,2,2,2',
		'style-class' => 'ep-collapsed',
		'comment_title_visibility' => array(
			'data-input-type' 			=> 'switch',
			'data-css-attribute'		=> 'display',
			'switch-type'				=> 'twoway',
			'title'		 				=> 'Visibility',
			'size'		 				=> 'span4',
			'class'						=> $args['handler'],
			'data-handler'				=> 'blog',
			'default' 	 				=> 'visible',
			'data-target'				=> '.comments-title',
			'style-class'	=> 'hide-for-default-blog',
			'switch-values' => array(
				'visible'	=> 'Visible',
				'hidden'  	=> 'Hidden',
			),
		),
		'comment_title_color' => array(
			'title'			=> 'Color',
			'data-css-attribute' => 'color',
			'size'			=> 'span2',
			'data-input-type'	=> 'color',
			'data-target'	=> '.comments-title',
			'default'		=> 'transparent',
			'class'			=> 'color-picker admin-listen-handler',
			'data-handler'  => 'colorPicker',
			'data-has-unit'	=> false,
			'data-picker'   => 'blog',
		),
		'comment_title_align' => array(
			'data-input-type' => 'select-box',
			'data-css-attribute' => 'text-align',
			'title'		 => 'Align',
			'size'		 => 'span2',
			'class'			=> $args['handler'],
			'data-handler'	=> 'blog',
			'data-target'=> '.comments-title',
			'default' 	 => 'left',
			'select-box-values' => array(
				'left'			=> 'Left',
				'center'		=> 'Center',
				'right'			=> 'Right',
			),
		),
		'comment_title_font_family' => array(
			'title'				=> 'Font Family',
			'size'				=> 'span2',
			'data-input-type'	=> 'select-fonts',
			'class'				=> $args['handler'],
			'data-handler'  	=> 'blog',
			'data-target'		=> '.comments-title',
			'select-box-values' => $this->fonts,
			'help'				=> 'No live preview available.',
		),
		'comment_title_font_size' => array(
			'title'			=> 'Font Size',
			'data-css-attribute' => 'font-size',
			'size'			=> 'span2',
			'offset'		=> false,
			'data-input-type' 	=> 'range-slider',
			'default'		=> 30,
			'min'			=> 0,
			'max'			=> 999,
			'class'			=> $args['handler'],
			'data-target'   => '.comments-title',
			'data-handler'	=> 'blog',
			'data-range-slider' => 'blog',
			'data-has-unit'	=> true,
		),
		'comment_title_padding_top' => array(
			'title'			=> 'Padding Top',
			'size'			=> 'span2',
			'offset'		=> false,
			'data-input-type' => 'range-slider',
			'default'		=> 90,
			'min'			=> 0,
			'max'			=> 999,
			'class'				=> $args['handler'],
			'data-handler'		=> 'blog',
			'data-range-slider' => 'blog',
			'data-has-unit'	=> true,
			'data-target'   => '.comments-title',
			'style-class'	=> 'hide-for-default-blog',
		),
		'comment_title_padding_bottom' => array(
			'title'			=> 'Padding Top',
			'size'			=> 'span2',
			'offset'		=> false,
			'data-input-type' => 'range-slider',
			'default'		=> 60,
			'min'			=> 0,
			'max'			=> 999,
			'class'				=> $args['handler'],
			'data-handler'		=> 'blog',
			'data-range-slider' => 'blog',
			'data-has-unit'	=> true,
			'data-target'   => '.comments-title',
			'style-class'	=> 'hide-for-default-blog',
		),
	),
	'author-options' => array(
		'title' => 'Author',
		'break'	=> '3',
		'style-class' => 'ep-collapsed',
		'comment_author_font_family' => array(
			'title'				=> 'Font Family',
			'size'				=> 'span2',
			'data-input-type'	=> 'select-fonts',
			'class'				=> $args['handler'],
			'data-handler'  	=> 'blog',
			'data-target'		=> '.comment-author',
			'select-box-values' => $this->fonts,
		),
		'comment_author_color' => array(
			'title'			=> 'Color',
			'data-css-attribute' => 'color',
			'size'			=> 'span1',
			'data-input-type'	=> 'color',
			'data-target'	=> '.comment-author cite, .comment-author cite a',
			'default'		=> '#000000',
			'class'			=> 'color-picker admin-listen-handler',
			'data-handler'  => 'colorPicker',
			'data-has-unit'	=> false,
			'data-picker'   => 'blog',
		),
		'comment_author_mouseover_color' => array(
			'title'			=> 'Hover',
			'size'			=> 'span1',
			'data-input-type'	=> 'color',
			'default'		=> '#000000',
			'class'			=> 'color-picker admin-listen-handler',
			'data-handler'  => 'colorPicker',
			'data-has-unit'	=> false,
			'data-picker'   => 'blog',
		),
	),
	'date-options' => array(
		'title' => 'Date',
		'break'	=> '3',
		'style-class' => 'ep-collapsed',
		'comment_date_font_family' => array(
			'title'				=> 'Font Family',
			'size'				=> 'span2',
			'data-input-type'	=> 'select-fonts',
			'class'				=> $args['handler'],
			'data-handler'  	=> 'blog',
			'data-target'		=> '.comment-meta a',
			'select-box-values' => $this->fonts,
		),
		'comment_date_color' => array(
			'title'			=> 'Color',
			'data-css-attribute' => 'color',
			'size'			=> 'span1',
			'data-input-type'	=> 'color',
			'data-target'	=> '.comment-meta a',
			'default'		=> '#666666',
			'class'			=> 'color-picker admin-listen-handler',
			'data-handler'  => 'colorPicker',
			'data-has-unit'	=> false,
			'data-picker'   => 'blog',
		),
		'comment_date_mouseover_color' => array(
			'title'			=> 'Hover',
			'size'			=> 'span1',
			'data-input-type'	=> 'color',
			'default'		=> '#000000',
			'class'			=> 'color-picker admin-listen-handler',
			'data-handler'  => 'colorPicker',
			'data-has-unit'	=> false,
			'data-picker'   => 'blog',
		),
	),
	'content-options' => array(
		'title' => 'Comment',
		'break'	=> '3,2',
		'style-class' => 'ep-collapsed',
		'comment_content_font_family' => array(
			'title'				=> 'Font Family',
			'size'				=> 'span2',
			'data-input-type'	=> 'select-fonts',
			'class'				=> $args['handler'],
			'data-handler'  	=> 'blog',
			'data-target'		=> '.comment-content',
			'select-box-values' => $this->fonts,
			'help'				=> 'No live preview available.',
		),
		'comment_content_color' => array(
			'title'			=> 'Color',
			'data-css-attribute' => 'color',
			'size'			=> 'span1',
			'data-input-type'	=> 'color',
			'data-target'	=> '.comment-content',
			'default'		=> '#292a2c',
			'class'			=> 'color-picker admin-listen-handler',
			'data-handler'  => 'colorPicker',
			'data-has-unit'	=> false,
			'data-picker'   => 'blog',
		),
		'comment_content_divider_color' => array(
			'title'			=> 'Divider',
			'data-css-attribute' => 'border-color',
			'size'			=> 'span1',
			'data-input-type'	=> 'color',
			'data-target'	=> '.comment, .comment .depth-2, .comment .depth-3',
			'default'		=> '#d6d6d6',
			'class'			=> 'color-picker admin-listen-handler',
			'data-handler'  => 'colorPicker',
			'data-has-unit'	=> false,
			'data-picker'   => 'blog',
		),
		'comment_content_font_size' => array(
			'title'			=> 'Font Size',
			'data-css-attribute' => 'font-size',
			'size'			=> 'span2',
			'offset'		=> false,
			'data-input-type' 	=> 'range-slider',
			'default'		=> 16,
			'min'			=> 0,
			'max'			=> 999,
			'class'			=> $args['handler'],
			'data-target'   => '.comment-content',
			'data-handler'	=> 'blog',
			'data-range-slider' => 'blog',
			'data-has-unit'	=> true,
		),
		'comment_content_line_height' => array(
			'title'			=> 'Line Height',
			'data-css-attribute' => 'line-height',
			'size'			=> 'span2',
			'offset'		=> false,
			'data-input-type' 	=> 'range-slider',
			'default'		=> 27,
			'min'			=> 0,
			'max'			=> 999,
			'class'			=> $args['handler'],
			'data-target'   => '.comment-content',
			'data-handler'	=> 'blog',
			'data-range-slider' => 'blog',
			'data-has-unit'	=> true,
		),
	),
	'reply-button-options' => array(
		'title' => 'Reply Button',
		'break'	=> '1,3',
		'style-class' => 'ep-collapsed',
		'comment_reply_bg_color' => array(
			'title'			=> 'Background Color',
			'data-css-attribute' => 'background-color',
			'size'			=> 'span4',
			'data-input-type'	=> 'color',
			'data-target'		=> '.comment-reply-link, #cancel-comment-reply-link',
			'default'		=> '#ffffff',
			'class'			=> 'color-picker admin-listen-handler',
			'data-handler'  => 'colorPicker',
			'data-has-unit'	=> false,
			'data-picker'   => 'blog',
		),
		'comment_reply_font_family' => array(
			'title'				=> 'Font Family',
			'size'				=> 'span2',
			'data-input-type'	=> 'select-fonts',
			'class'				=> $args['handler'],
			'data-handler'  	=> 'blog',
			'data-target'		=> '.comment-reply-link, #cancel-comment-reply-link',
			'select-box-values' => $this->fonts,
		),
		'comment_reply_color' => array(
			'title'			=> 'Color',
			'data-css-attribute' => 'color',
			'size'			=> 'span1',
			'data-input-type'	=> 'color',
			'data-target'	=> '.comment-reply-link, #cancel-comment-reply-link',
			'default'		=> '#666666',
			'class'			=> 'color-picker admin-listen-handler',
			'data-handler'  => 'colorPicker',
			'data-has-unit'	=> false,
			'data-picker'   => 'blog',
		),
		'comment_reply_border_color' => array(
			'title'			=> 'Border',
			'data-css-attribute' => 'border-color',
			'size'			=> 'span1',
			'data-input-type'	=> 'color',
			'data-target'	=> '.comment-reply-link, #cancel-comment-reply-link',
			'default'		=> '#e6e6e6',
			'class'			=> 'color-picker admin-listen-handler',
			'data-handler'  => 'colorPicker',
			'data-has-unit'	=> false,
			'data-picker'   => 'blog',
		),
	),
	'respond-options' => array(
		'title' => 'Respond Title',
		'break'	=> '2',
		'style-class' => 'ep-collapsed',
		'comment_respond_font_family' => array(
			'title'				=> 'Font Family',
			'size'				=> 'span2',
			'data-input-type'	=> 'select-fonts',
			'class'				=> $args['handler'],
			'data-handler'  	=> 'blog',
			'data-target'		=> '#reply-title',
			'select-box-values' => $this->fonts,
		),
		'comment_respond_color' => array(
			'title'			=> 'Title Color',
			'data-css-attribute' => 'color',
			'size'			=> 'span2',
			'data-input-type'	=> 'color',
			'data-target'	=> '#reply-title',
			'default'		=> '#292a2c',
			'class'			=> 'color-picker admin-listen-handler',
			'data-handler'  => 'colorPicker',
			'data-has-unit'	=> false,
			'data-picker'   => 'blog',
		),
	),
	'input-options' => array(
		'title' => 'Form Options',
		'break'	=> '2,3',
		'style-class' => 'ep-collapsed',
		'comment_form_bg_color' => array(
			'title'			=> 'Background Color',
			'data-css-attribute' => 'background-color',
			'size'			=> 'span2',
			'data-input-type'	=> 'color',
			'data-target'	=> '#commentform .comment-input input, #commentform textarea',
			'default'		=> '#f9f9f9',
			'class'			=> 'color-picker admin-listen-handler',
			'data-handler'  => 'colorPicker',
			'data-has-unit'	=> false,
			'data-picker'   => 'blog',
		),
		'comment_form_placeholder_color' => array(
			'title'			=> 'Placeholder Color',
			'data-css-attribute' => 'color',
			'size'			=> 'span2',
			'data-input-type'	=> 'color',
			'data-target'	=> '',
			'default'		=> '#b3b3b3',
			'class'			=> 'color-picker admin-listen-handler',
			'data-handler'  => 'colorPicker',
			'data-has-unit'	=> false,
			'data-picker'   => 'blog',
			'help'			=> 'There is no preview for this setting.',
		),
		'comment_form_font_family' => array(
			'title'				=> 'Font Family',
			'size'				=> 'span2',
			'data-input-type'	=> 'select-fonts',
			'class'				=> $args['handler'],
			'data-handler'  	=> 'blog',
			'data-target'		=> '#commentform .comment-input input, #commentform textarea',
			'select-box-values' => $this->fonts,
		),
		'comment_form_color' => array(
			'title'			=> 'Color',
			'data-css-attribute' => 'color',
			'size'			=> 'span1',
			'data-input-type'	=> 'color',
			'data-target'	=> '#commentform .comment-input input, #commentform textarea',
			'default'		=> '#000000',
			'class'			=> 'color-picker admin-listen-handler',
			'data-handler'  => 'colorPicker',
			'data-has-unit'	=> false,
			'data-picker'   => 'blog',
		),
		'comment_form_border_color' => array(
			'title'			=> 'Border',
			'data-css-attribute' => 'border-color',
			'size'			=> 'span1',
			'data-input-type'	=> 'color',
			'data-target'	=> '#commentform .comment-input input, #commentform textarea',
			'default'		=> '#e0e0e0',
			'class'			=> 'color-picker admin-listen-handler',
			'data-handler'  => 'colorPicker',
			'data-has-unit'	=> false,
			'data-picker'   => 'blog',
		),
	),
	'submit-options' => array(
		'title' => 'Submit Options',
		'break'	=> '1,3',
		'style-class' => 'ep-collapsed',
		'comment_submit_bg_color' => array(
			'title'			=> 'Background Color',
			'data-css-attribute' => 'background-color',
			'size'			=> 'span4',
			'data-input-type'	=> 'color',
			'data-target'	=> '#commentform #submit',
			'default'		=> '#f9f9f9',
			'class'			=> 'color-picker admin-listen-handler',
			'data-handler'  => 'colorPicker',
			'data-has-unit'	=> false,
			'data-picker'   => 'blog',
		),
		'comment_submit_font_family' => array(
			'title'				=> 'Font Family',
			'size'				=> 'span2',
			'data-input-type'	=> 'select-fonts',
			'class'				=> $args['handler'],
			'data-handler'  	=> 'blog',
			'data-target'	=> '#commentform #submit',
			'select-box-values' => $this->fonts,
		),
		'comment_submit_color' => array(
			'title'			=> 'Color',
			'data-css-attribute' => 'color',
			'size'			=> 'span1',
			'data-input-type'	=> 'color',
			'data-target'	=> '#commentform #submit',
			'default'		=> '#000000',
			'class'			=> 'color-picker admin-listen-handler',
			'data-handler'  => 'colorPicker',
			'data-has-unit'	=> false,
			'data-picker'   => 'blog',
		),
		'comment_submit_border_color' => array(
			'title'			=> 'Border',
			'data-css-attribute' => 'border-color',
			'size'			=> 'span1',
			'data-input-type'	=> 'color',
			'data-target'	=> '#commentform #submit',
			'default'		=> '#e0e0e0',
			'class'			=> 'color-picker admin-listen-handler',
			'data-handler'  => 'colorPicker',
			'data-has-unit'	=> false,
			'data-picker'   => 'blog',
		),
	),
);