<?php

// -----------------------------------------
// semplice
// admin/atts/modules/blogarchives.php
// -----------------------------------------

$blogarchives = array(
	'refresh-grid' => array(
		'title'  	 => 'Refresh',
		'hide-title' => true,
		'break'		 => '1',
		'refresh' => array(
			'data-input-type' 	=> 'button',
			'title'		 		=> 'Preview',
			'button-title'		=> 'Refresh preview',
			'hide-title'		=> true,
			'size'		 		=> 'span4',
			'class'				=> 'semplice-button regenerate-blogarchives',
			'responsive'		=> true,
		),
	),
	'general-options' => array(
		'title'  	 => 'General options',
		'break'		 => '2,1,1,1,1,1',
		'hide-title' => true,
		'data-hide-mobile' => true,
		'type' => array(
			'data-input-type' => 'select-box',
			'title'		 => 'Archive Type',
			'size'		 => 'span2',
			'class'			=> 'editor-listen',
			'data-target'=> '.is-content',
			'data-handler'  => 'save',
			'default' 	 => 'category',
			'data-visibility-switch' 	=> true,
			'data-visibility-values' 	=> 'category,latest,post_tag,authors,posts',
			'data-visibility-prefix'	=> 'ov-blog-archive',
			'select-box-values' => array(
				'category' 		=> 'Categories',
				'latest'		=> 'Recent Posts',
				'post_tag'		=> 'Tags',
				'authors' 		=> 'Authors',
				'posts'			=> 'Posts'
			),
		),
		'limit' => array(
			'title'			=> 'Limit',
			'help'			=> 'Define the maximum number of list items.<br /><br />Your limit is ignored once you select your categories, tags or posts manually.',
			'size'			=> 'span2',
			'offset'		=> false,
			'data-input-type' 	=> 'range-slider',
			'default'		=> 10,
			'min'			=> 0,
			'max'			=> 99999,
			'class'			=> 'editor-listen',
			'data-handler'  => 'save',
		),
		'categories' => array(
			'data-input-type' 	=> 'button',
			'title'		 		=> 'Categories',
			'button-title'		=> 'Select Categories',
			'size'		 		=> 'span4',
			'class'				=> 'semplice-button white-button expand-options admin-click-handler',
			'data-target'		=> 'category',
			'data-expand-options' => 'taxonomy',
			'style-class'		=> 'ov-blog-archive-category'
		),
		'tags' => array(
			'data-input-type' 	=> 'button',
			'title'		 		=> 'Tags',
			'button-title'		=> 'Select Tags',
			'size'		 		=> 'span4',
			'class'				=> 'semplice-button white-button expand-options admin-click-handler',
			'data-target'		=> 'tag',
			'data-expand-options' => 'taxonomy',
			'style-class'		=> 'ov-blog-archive-post_tag'
		),
		'authors' => array(
			'data-input-type' 	=> 'button',
			'title'		 		=> 'Authors',
			'button-title'		=> 'Select Authors',
			'size'		 		=> 'span4',
			'class'				=> 'semplice-button white-button expand-options admin-click-handler',
			'data-target'		=> 'author',
			'data-expand-options' => 'taxonomy',
			'style-class'		=> 'ov-blog-archive-authors'
		),
		'posts' => array(
			'data-input-type' 	=> 'button',
			'title'		 		=> 'Posts',
			'button-title'		=> 'Select Posts',
			'size'		 		=> 'span4',
			'class'				=> 'semplice-button white-button expand-options admin-click-handler',
			'data-target'		=> 'post',
			'data-expand-options' => 'taxonomy',
			'style-class'		=> 'ov-blog-archive-posts'
		),
	),
	'formatting-options' => array(
		'title'  	 => 'Type Formatting',
		'break'		 => '2,2,2,2,2',
		'style-class'	=> 'ep-collapsed',
		'data-hide-mobile' => true,
		'color' => array(
			'title'				=> 'Text Color',
			'data-style-option' => true,
			'size'				=> 'span2',
			'data-input-type'	=> 'color',
			'default'			=> '#000000',
			'class'				=> 'color-picker admin-listen-handler',
			'data-handler' 		=> 'colorPicker',
			'data-picker'		=> 'blogarchives'
		),
		'mouseover_color' => array(
			'title'				=> 'Mouseover Color',
			'data-style-option' => true,
			'size'				=> 'span2',
			'data-input-type'	=> 'color',
			'default'			=> '#000000',
			'class'				=> 'color-picker admin-listen-handler',
			'data-handler' 		=> 'colorPicker',
			'data-picker'		=> 'blogarchives'
		),
		'align' => array(
			'data-input-type' => 'select-box',
			'title'		 => 'Align',
			'size'		 => 'span2',
			'class'			=> 'editor-listen',
			'data-handler'	=> 'blogarchives',
			'default' 	 => 'left',
			'select-box-values' => array(
				'left'			=> 'Left',
				'center'		=> 'Center',
				'right'			=> 'Right',
			),
		),
		'text_transform' => array(
			'data-input-type' => 'select-box',
			'title'		 => 'Text Transform',
			'size'		 => 'span2',
			'class'			=> 'editor-listen',
			'data-handler'	=> 'blogarchives',
			'default' 	 => 'none',
			'select-box-values' => array(
				'none'			=> 'None',
				'uppercase'		=> 'Uppercase',
				'lowercase'		=> 'Lowercase'
			),
		),
		'font_family' => array(
			'data-input-type' => 'select-fonts',
			'title'		 		=> 'Font Family',
			'size'		 		=> 'span2',
			'class'     		=> 'editor-listen',
			'data-handler'  	=> 'blogarchives',
			'default' 	 		=> 'none',
			'select-box-values' => $atts->fonts,
		),
		'font_size' => array(
			'title'			=> 'Font Size',
			'size'			=> 'span2',
			'offset'		=> false,
			'data-input-type' 	=> 'range-slider',
			'default'		=> 18,
			'min'			=> 6,
			'max'			=> 999,
			'class'     	=> 'editor-listen',
			'data-handler'  => 'blogarchives',
			'data-range-slider' => 'blogarchives',
			'data-has-unit'	=> true,
		),
		'line_height' => array(
			'title'			=> 'Line Height',
			'size'			=> 'span2',
			'offset'		=> false,
			'data-input-type' 	=> 'range-slider',
			'default'		=> 26,
			'min'			=> 0,
			'max'			=> 999,
			'class'     	=> 'editor-listen',
			'data-handler'  => 'blogarchives',
			'data-range-slider' => 'blogarchives',
			'data-has-unit'	=> true,
		),
		'letter_spacing' => array(
			'title'				=> 'Letter Spacing',
			'size'				=> 'span2',
			'data-input-type' 	=> 'range-slider',
			'default'			=> 0,
			'min'				=> 0,
			'max'				=> 9999,
			'data-negative' 	=> true,
			'data-has-unit'		=> true,
			'data-divider'		=> 10,
			'class' 	 		=> 'editor-listen',
			'data-handler'		=> 'blogarchives',
			'data-range-slider' => 'blogarchives'
		),
		'padding_ver' => array(
			'title'			=> 'Padding Ver',
			'size'			=> 'span2',
			'offset'		=> false,
			'data-input-type' 	=> 'range-slider',
			'default'		=> 10,
			'min'			=> 0,
			'max'			=> 999,
			'class'     	=> 'editor-listen',
			'data-handler'  => 'blogarchives',
			'data-range-slider' => 'blogarchives',
			'data-has-unit'	=> true,
		),
		'padding_hor' => array(
			'title'			=> 'Padding Hor',
			'size'			=> 'span2',
			'offset'		=> false,
			'data-input-type' 	=> 'range-slider',
			'default'		=> 0,
			'min'			=> 0,
			'max'			=> 999,
			'class'     	=> 'editor-listen',
			'data-handler'  => 'blogarchives',
			'data-range-slider' => 'blogarchives',
			'data-has-unit'	=> true,
		),
	),
	'seperator-options' => array(
		'title'  	 => 'Seperator',
		'break'		 => '2',
		'style-class'	=> 'ep-collapsed',
		'data-hide-mobile' => true,
		'seperator_height' => array(
			'title'			=> 'Height',
			'size'			=> 'span2',
			'offset'		=> false,
			'data-input-type' 	=> 'range-slider',
			'default'		=> 1,
			'min'			=> 0,
			'max'			=> 999,
			'class'     	=> 'editor-listen',
			'data-handler'  => 'blogarchives',
			'data-range-slider' => 'blogarchives',
			'data-has-unit'	=> true,
		),
		'seperator_color' => array(
			'title'				=> 'Color',
			'data-style-option' => true,
			'size'				=> 'span2',
			'data-input-type'	=> 'color',
			'default'			=> '#b0b0b0',
			'class'				=> 'color-picker admin-listen-handler',
			'data-handler' 		=> 'colorPicker',
			'data-picker'		=> 'blogarchives'
		),
	),
	// mobile blogarchive options
	'blogarchive_responsive_lg' => $atts->get_mobile('blogarchive', 'Desktop', 'lg', false),
	'blogarchive_responsive_md' => $atts->get_mobile('blogarchive', 'Tablet Landscape', 'md', false),
	'blogarchive_responsive_sm' => $atts->get_mobile('blogarchive', 'Tablet Portrait', 'sm', false),
	'blogarchive_responsive_xs' => $atts->get_mobile('blogarchive', 'Mobile', 'xs', false),
);

?>