<?php

// -----------------------------------------
// semplice
// admin/atts/modules/gallery.php
// -----------------------------------------

$gallery = array(
	'uploads' => array(
		'title' => 'Images',
		'break' => '1,2,2',
		'data-hide-mobile' => true,
		'images' => array(
			'title'				=> 'Images',
			'hide-title'		=> true,
			'data-style-option' => true,
			'size'				=> 'span4',
			'data-input-type'	=> 'gallery-upload',
			'default'			=> '',
			'data-is-content' 	=> true,
			'class'      		=> 'editor-listen',
			'data-handler' 		=> 'save',
			'style-class'		=> 'ce-dropzone ce-dropzone-no-unsplash gallery-upload video-support',
		),
		'animation_status' => array(
			'data-input-type' => 'switch',
			'switch-type'=> 'twoway',
			'title'		 => 'Animation',
			'size'		 => 'span2',
			'class'      		=> 'editor-listen',
			'data-handler' 		=> 'save',
			'default' 	 => 'enabled',
			'switch-values' => array(
				'enabled'		=> 'On',
				'disabled'	 	=> 'Off',
			),
		),
		'animation' => array(
			'data-input-type' => 'switch',
			'switch-type'=> 'twoway',
			'title'		 => 'Type',
			'size'		 => 'span2',
			'class'      		=> 'editor-listen',
			'data-handler' 		=> 'save',
			'default' 	 => 'sgs-crossfade',
			'data-visibility-switch' 	=> true,
			'data-visibility-values' 	=> 'sgs-crossfade,sgs-slide',
			'data-visibility-prefix'	=> 'ov-gal-animation',
			'switch-values' => array(
				'sgs-crossfade'	=> 'Fade',
				'sgs-slide'	 	=> 'Slide',
			),
		),
		'attraction' => array(
			'title'			=> 'Attraction',
			'size'			=> 'span2',
			'offset'		=> false,
			'data-input-type' 	=> 'range-slider',
			'default'		=> 25,
			'min'			=> 0,
			'max'			=> 9999,
			'data-divider'  => 1000,
			'class'      	=> 'editor-listen',
			'data-handler' 	=> 'save',
			'help'			=> 'Attracts the position of the slider to the selected slide. Higher attraction makes the slider move faster. Lower makes it move slower.',
		),
		'friction' => array(
			'title'			=> 'Friction',
			'size'			=> 'span2',
			'offset'		=> false,
			'data-input-type' 	=> 'range-slider',
			'default'		=> 280,
			'min'			=> 0,
			'max'			=> 9999,
			'data-divider'  => 1000,
			'class'      	=> 'editor-listen',
			'data-handler' 	=> 'save',
			'help'			=> 'Slows the movement of slider. Higher friction makes the slider feel stickier and less bouncy. Lower friction makes the slider feel looser and more wobbly.',
		),
	),
	'layout-options' => array(
		'title' => 'Layout options',
		'break' => '1,2,2,2,2',
		'data-hide-mobile' => true,
		'style-class' => 'ep-collapsed',
		'show_options' => array(
			'data-input-type' => 'notice',
			'hide-title' => true,
			'size'		 => 'span4',
			'class'     	=> 'ep-notice',
			'data-handler'  => 'mailchimp',
			'default'    => '<b>Note:</b> With disabled or fade animations you will only see one slide at a time despite your layout options. Please see <a href="https://help.semplice.com/hc/en-us/articles/4524356942868" target="_blank">our guide</a> for the new layout options.',
			'notice-type'=> 'warning',
		),
		'slide_width' => array(
			'data-input-type' => 'select-box',
			'title'		 => 'Slide Width',
			'size'		 => 'span2',
			'class'      		=> 'editor-listen',
			'data-handler' 		=> 'save',
			'default' 	 => 'grid',
			'help'  	 => '<b>Grid Width</b><br />Your slides will have the width of the grid so you will only see one active image in your slider.<br /><br /><b>Image Width</b><br />Your slides will have the width of your images so all of your slides will get displayed side by side and you can see the next and previous images. (unless your image size exceeds the slide width)<br /><br /><b>Custom Width</b><br />Define your custom slide width in %.</b>',
			'data-visibility-switch' 	=> true,
			'data-visibility-values' 	=> 'disabled,grid,image,custom',
			'data-visibility-prefix'	=> 'ov-gal-slide-width',
			'select-box-values' => array(
				'grid'	 => 'Grid Width',
				'image'  => 'Image Width',
				'custom' => 'Custom'
			),
		),
		'slide_width_custom' => array(
			'title'			=> 'Custom Width (%)',
			'size'			=> 'span2',
			'offset'		=> false,
			'data-input-type' 	=> 'range-slider',
			'default'		=> 100,
			'min'			=> 1,
			'max'			=> 100,
			'class'      	=> 'editor-listen',
			'data-handler' 	=> 'save',
			'style-class'	=> 'ov-gal-slide-width-custom'
		),
		'width' => array(
			'data-input-type' => 'select-box',
			'title'		 	  => 'Image Width',
			'size'		 	  => 'span2',
			'class'      		=> 'editor-listen',
			'data-handler' 		=> 'save',
			'default' 	 	  => 'grid-width',
			'help'		 => '<b>Slide width</b><br />This will scale your images to the width of your slide. (which you can change above)<br /><br /><b>Max Width</b><br />Define a maximum width of your image in %. Your image will never exceed that width.<br /><br /><b>Original</b><br />Display your images at it\'s original size (unless they are bigger than the slide) and horizontally centered.',
			'data-visibility-switch' 	=> true,
			'data-visibility-values' 	=> 'disabled,grid-width,max-width,original',
			'data-visibility-prefix'	=> 'ov-gal-image-width',
			'select-box-values' => array(
				'grid-width'	=> 'Slide Width',
				'max-width'		=> 'Set maximum width',
				'original'	 	=> 'Original',
			),
		),
		'max_width' => array(
			'title'			=> 'Image Max Width (%)',
			'size'			=> 'span2',
			'offset'		=> false,
			'data-input-type' 	=> 'range-slider',
			'default'		=> 100,
			'min'			=> 1,
			'max'			=> 100,
			'class'      	=> 'editor-listen',
			'data-handler' 	=> 'save',
			'style-class'	=> 'ov-gal-image-width-max-width'
		),
		'height' => array(
			'data-input-type' => 'select-box',
			'title'		 	  => 'Image Height',
			'size'		 	  => 'span2',
			'class'      		=> 'editor-listen',
			'data-handler' 		=> 'save',
			'default' 	 	  => 'grid-width',
			'help'		 => '<b>Auto</b><br />Auto means that the height of your images is gets set automatically based on the width and ratio of your image.<br /><br /><b>Maximum Height</b><br />Set a maximum height in % of your viewport. Your image will never exceed that maximum height. Don\'t forget to also set the image width otherwise images could get cropped.',
			'data-visibility-switch' 	=> true,
			'data-visibility-values' 	=> 'disabled,auto,max-height',
			'data-visibility-prefix'	=> 'ov-gal-image-height',
			'select-box-values' => array(
				'auto'	=> 'Auto',
				'max-height'	=> 'Set maximum height',
			),
		),
		'max_height' => array(
			'title'			=> 'Image Max Height (%)',
			'size'			=> 'span2',
			'offset'		=> false,
			'data-input-type' 	=> 'range-slider',
			'default'		=> 75,
			'min'			=> 1,
			'max'			=> 100,
			'class'      	=> 'editor-listen',
			'data-handler' 	=> 'save',
			'style-class'	=> 'ov-gal-image-height-max-height'
		),
		'spacing' => array(
			'title'			=> 'Image Spacing',
			'size'			=> 'span2',
			'offset'		=> false,
			'data-input-type' 	=> 'range-slider',
			'default'		=> 0,
			'min'			=> 1,
			'max'			=> 999,
			'data-has-unit' => true,
			'class'      	=> 'editor-listen',
			'data-handler' 	=> 'save',
			'help'			=> 'Only takes affect if \'Slide Width\' is set to \'Image Width\' or \'Custom\'.',
			'data-supported-units' => 'rem,%,vw'
		),
		'vertical_align' => array(
			'data-input-type' => 'switch',
			'switch-type'=> 'twoway',
			'title'		 => 'Image Alignment',
			'size'		 => 'span2',
			'class'      		=> 'editor-listen',
			'data-handler' 		=> 'save',
			'default' 	 => 'flex-start',
			'help'		 => 'Define the vertical alignment of your images. Will only take affect if your images doesn\'t share the same height.',
			'switch-values' => array(
				'flex-start' => 'Top',
				'center'  	 => 'Center',
			),
		),
	),
	'freescroll-option' => array(
		'title' => 'Freescroll',
		'break' => '1',
		'data-hide-mobile' => true,
		'hide-title' => true,
		'style-class' => 'relative',
		'freescroll' => array(
			'data-input-type' => 'onoff-switch',
			'help' => 'If enabled you can use drag and drop to scroll your images. Animation settings, next/prev and pagination will be disabled for this option.',
			'hide-title' => true,
			'title'		 => 'Freescroll',
			'size'		 => 'span2',
			'class'      		=> 'editor-listen',
			'data-handler' 		=> 'save',
			'default' 	 => 'false',
			'data-on'		  => 'true',
			'data-off'		  => 'false',
		),
	),
	'cover-option' => array(
		'title' => 'Cover',
		'break' => '1',
		'data-hide-mobile' => true,
		'hide-title' => true,
		'style-class' => 'relative',
		'cover_mode' => array(
			'data-input-type' => 'onoff-switch',
			'help' => 'If enabled your image gallery will be full width and full height like a cover.<br /><br />Only exception is that if your section has a custom height the gallery cover mode will use that height instead.<br /><br />When cover mode is enabled all layout settings will be ignored.<br /><br /><b>Important:</b><br/>To make this work please make sure that you only have 1 column in your section and that your section width is set to fluid with no gutters.',
			'hide-title' => true,
			'title'		 => 'Cover Mode',
			'size'		 => 'span2',
			'class'      		=> 'editor-listen',
			'data-handler' 		=> 'save',
			'default' 	 => 'disabled',
			'data-on'		  => 'enabled',
			'data-off'		  => 'disabled',
		),
	),
	'autoplay-option' => array(
		'title' => 'Cover',
		'break' => '1,1',
		'data-hide-mobile' => true,
		'hide-title' => true,
		'style-class' => 'relative',
		'autoplay' => array(
			'data-input-type' => 'onoff-switch',
			'title'		 => 'Autoplay',
			'hide-title' => true,
			'size'		 => 'span2',
			'class'      		=> 'editor-listen',
			'data-handler' 		=> 'save',
			'default' 	 => 'false',
			'data-visibility-switch' 	=> true,
			'data-visibility-values' 	=> 'true,false',
			'data-visibility-prefix'	=> 'ov-gal-autoplay',
			'data-on'		  => 'true',
			'data-off'		  => 'false',
		),
		'timeout' => array(
			'data-input-type'	=> 'input-text',
			'title'		 	=> 'Timeout',
			'size'		 	=> 'span4',
			'placeholder'	=> '4000',
			'default'		=> '4000',
			'class'      		=> 'editor-listen',
			'data-handler' 		=> 'save',
			'style-class'	=> 'ov-gal-autoplay-true',
			'help'			=> 'This is the timeout between images in milliseconds. Minimum is 600ms.',
		),
	),
	'adaptive-height-option' => array(
		'title' => 'Cover',
		'break' => '1',
		'data-hide-mobile' => true,
		'hide-title' => true,
		'style-class' => 'relative',
		'adaptive_height' => array(
			'data-input-type' => 'onoff-switch',
			'hide-title' => true,
			'help'			  => 'If \'enabled\' the height of the gallery slider always adapts to the height of the active slide.',
			'title'		 => 'Adaptive Height',
			'size'		 => 'span2',
			'class'      		=> 'editor-listen',
			'data-handler' 		=> 'save',
			'default' 	 => 'true',
			'data-on'		  => 'true',
			'data-off'		  => 'false',
		),
	),
	'arrows' => array(
		'title' => 'Arrows',
		'break' => '2,2,2',
		'data-hide-mobile' => true,
		'style-class' => 'ep-collapsed',
		'arrows_visibility' => array(
			'data-input-type' => 'switch',
			'switch-type'=> 'twoway',
			'title'		 => 'Visibility',
			'size'		 => 'span2',
			'class'      		=> 'editor-listen',
			'data-handler' 		=> 'save',
			'default' 	 => 'true',
			'switch-values' => array(
				'true'	 => 'Show',
				'false'  => 'Hide',
			),
		),
		'arrows_color' => array(
			'data-css-attribute' => 'fill',
			'title'			=> 'Color',
			'size'			=> 'span2',
			'data-input-type'	=> 'color',
			'data-target'	=> '.flickity-button-icon path',
			'default'		=> '#ffffff',
			'class'			=> 'color-picker admin-listen-handler',
			'data-handler'  => 'colorPicker',
		),
		'arrows_shape' => array(
			'data-input-type' => 'select-box',
			'title'		 => 'Shape',
			'size'		 => 'span2',
			'class'      	=> 'editor-listen',
			'data-handler' 	=> 'save',
			'data-visibility-switch' 	=> true,
			'data-visibility-values' 	=> 'default,alternative,custom',
			'data-visibility-prefix'	=> 'ov-gallery-arrow',
			'default' 	 => 'default',
			'select-box-values' => array(
				'default' 		=> 'Default',
				'alternative' 	=> 'Alternative',
				'custom'		=> 'Custom',
			),
		),
		'arrows_custom' => array(
			'title'				=> 'Custom Shape',
			'help'				=> 'For correct sizing, draw the left arrow on a 100x100 canvas (right arrow will mirror it). If you edit your SVG in a text editor, be sure to copy & paste the ‘d’ attribute of your path string. We built a <a class="help-link" href="https://www.semplice.com/custom-arrows" target="_blank">little helper</a> for you.',
			'size'				=> 'span2',
			'data-input-type'	=> 'input-text',
			'default'			=> '',
			'class'				=> 'editor-listen',
			'placeholder'		=> 'SVG path string',
			'data-handler' 		=> 'save',
			'style-class'		=> 'ov-gallery-arrow-custom',
		),
		'arrows_bg_color' => array(
			'data-css-attribute' => 'background-color',
			'title'			=> 'Background',
			'size'			=> 'span2',
			'data-input-type'	=> 'color',
			'data-target'	=> '.flickity-button',
			'default'		=> '#000000',
			'class'			=> 'color-picker admin-listen-handler',
			'data-handler'  => 'colorPicker',
		),
		'arrows_bg_opacity' => array(
			'title'			=> 'BG Opacity',
			'size'			=> 'span2',
			'offset'		=> false,
			'data-input-type' => 'range-slider',
			'default'		=> 0,
			'min'			=> 0,
			'max'			=> 100,
			'class'				=> 'editor-listen',
			'data-handler'		=> 'save',
		),
	),
	'pagination' => array(
		'title' => 'Pagination',
		'break' => '2,2',
		'data-hide-mobile' => true,
		'style-class' => 'ep-collapsed',
		'pagination_color' => array(
			'title'				=> 'Color',
			'data-style-option' => true,
			'size'				=> 'span2',
			'data-input-type'	=> 'color',
			'default'			=> '#000000',
			'class'				=> 'color-picker',
		),
		'pagination_visibility' => array(
			'data-input-type' => 'switch',
			'switch-type'=> 'twoway',
			'title'		 => 'Visibility',
			'size'		 => 'span2',
			'class'      		=> 'editor-listen',
			'data-handler' 		=> 'save',
			'default' 	 => 'false',
			'switch-values' => array(
				'true'	 => 'Show',
				'false'  => 'Hide',
			),
		),
		'pagination_style' => array(
			'data-input-type' => 'switch',
			'switch-type'=> 'twoway',
			'title'		 => 'Style',
			'size'		 => 'span2',
			'class'      		=> 'editor-listen',
			'data-handler' 		=> 'save',
			'default' 	 => 'dots',
			'switch-values' => array(
				'dots'	 => 'Dots',
				'lines'  => 'Lines',
			),
		),
		'pagination_position' => array(
			'data-input-type' => 'select-box',
			'title'		 => 'Position',
			'size'		 => 'span2',
			'class'      		=> 'editor-listen',
			'data-handler' 		=> 'save',
			'default' 	 => 'below',
			'select-box-values' => array(
				'below'	 => 'Below Image',
				'above'  => 'Above Image',
			),
		),
	),
	'caption' => array(
		'title' => 'Caption',
		'break' => '1,2,2',
		'data-hide-mobile' => true,
		'style-class' => 'ep-collapsed',
		'caption_visibility' => array(
			'data-input-type' => 'switch',
			'switch-type'=> 'twoway',
			'title'		 => 'Visibility',
			'size'		 => 'span4',
			'class'      		=> 'editor-listen',
			'data-handler' 		=> 'save',
			'default' 	 => 'hidden',
			'help'		 => 'Captions will not be displayed if Cover Mode is enabled.',
			'switch-values' => array(
				'hidden'  => 'Hide',
				'visible' => 'Show',
			),
		),
		'caption_color' => array(
			'title'				=> 'Color',
			'data-style-option' => true,
			'size'				=> 'span2',
			'data-input-type'	=> 'color',
			'data-target'		=> '.spacer',
			'default'			=> '#000000',
			'class'				=> 'color-picker admin-listen-handler',
			'data-handler' 		=> 'colorPicker',	
		),
		'caption_font' => array(
			'data-input-type' => 'select-fonts',
			'title'		 		=> 'Font Family',
			'size'		 		=> 'span2',
			'class'				=> 'editor-listen',
			'data-handler'		=> 'save',
			'default' 	 		=> 'none',
			'select-box-values' => $atts->fonts,
		),
		'caption_fontsize' => array(
			'title'			=> 'Font Size',
			'size'			=> 'span2',
			'offset'		=> false,
			'data-input-type' 	=> 'range-slider',
			'default'		=> 16,
			'min'			=> 0,
			'max'			=> 999,
			'class'				=> 'editor-listen',
			'data-handler'		=> 'save',
			'data-style-option' => true,
			'data-has-unit'	=> true,
		),
		'caption_text_transform' => array(
			'title'				=> 'Text Transform',
			'size'				=> 'span2',
			'data-input-type'	=> 'select-box',
			'class'				=> 'editor-listen',
			'data-handler'		=> 'save',
			'default'			=> 'none',
			'select-box-values' => array(
				'none'			=> 'None',
				'uppercase'		=> 'Uppercase',
			),
		),
	),
	// mobile gallery options
	'gallery_responsive_lg' => $atts->get_mobile('gallery', 'Desktop', 'lg', false),
	'gallery_responsive_md' => $atts->get_mobile('gallery', 'Tablet Landscape', 'md', false),
	'gallery_responsive_sm' => $atts->get_mobile('gallery', 'Tablet Portrait', 'sm', false),
	'gallery_responsive_xs' => $atts->get_mobile('gallery', 'Mobile', 'xs', false),
);

?>