<?php

// -----------------------------------------
// semplice
// admin/atts/modules/marquee.php
// -----------------------------------------

$marquee = array(
	'marquee-options' => array(
		'title'  	 		=> 'Marquee Options',
		'break'		 		=> '2,2,1,2,1',
		'data-hide-mobile' 	=> true,
		'help'				=> 'To see your marquee in action please save your changes and click on the eye icon in the top bar to preview your page.',
		'mode' => array(
			'data-input-type' => 'switch',
			'switch-type'=> 'twoway',
			'title'		 => 'Mode',
			'size'		 => 'span2',
			'class'      	=> 'editor-listen',
			'data-handler' 	=> 'marquee',
			'default' 	 => 'text',
			'data-visibility-switch' 	=> true,
			'data-visibility-values' 	=> 'text,image',
			'data-visibility-prefix'	=> 'ov-marquee',
			'switch-values' => array(
				'text'	 => 'Text',
				'image' 	 => 'Image',
			),
		),
		'direction' => array(
			'data-input-type' => 'switch',
			'switch-type'=> 'twoway',
			'title'		 => 'Direction',
			'size'		 => 'span2',
			'class'      	=> 'editor-listen',
			'data-handler' 	=> 'marquee',
			'default' 	 => 'ltr',
			'help'		 => '<b>LTR</b>: Left to right<br /><b>RTL</b>: Right to left',
			'switch-values' => array(
				'ltr'	 => 'LTR',
				'rtl' 	 => 'RTL',
			),
		),
		'clones' => array(
			'title'			=> 'Clones',
			'size'			=> 'span2',
			'offset'		=> false,
			'data-input-type' 	=> 'range-slider',
			'default'		=> 3,
			'min'			=> 1,
			'max'			=> 30,
			'class'				=> 'editor-listen',
			'data-handler'		=> 'marquee',
			'data-range-slider' => 'marquee',
			'help'			=> 'In order to make a seamless marquee your content will get cloned and appended on the right. A white gap in the end means that you need more clones to fill the width.<br /><br />Just play around with it until you have a seamless marquee without any gap.',
		),
		'speed' => array(
			'title'			=> 'Speed',
			'size'			=> 'span2',
			'offset'		=> false,
			'data-input-type' 	=> 'range-slider',
			'default'		=> 200,
			'min'			=> 0,
			'max'			=> 9999,
			'class'				=> 'editor-listen',
			'data-handler'		=> 'save',
		),
	),
	'content-options' => array(
		'title'  	 		=> 'Content Options',
		'break'		 		=> '1,1,2,1',
		'data-hide-mobile' 	=> true,
		'style-class'		=> 'ep-collapsed',
		'text' => array(
			'data-input-type'	=> 'input-text',
			'title'		 	=> 'Text',
			'size'		 	=> 'span4',
			'placeholder'	=> 'Enter your marquee text',
			'default'		=> '',
			'class'      	=> 'editor-listen',
			'data-handler'	=> 'marquee',
			'style-class'	=> 'ov-marquee-text'
		),
		'images' => array(
			'title'				=> 'Images',
			'size'				=> 'span4',
			'data-input-type'	=> 'gallery-upload',
			'default'			=> '',
			'data-is-content' 	=> true,
			'class'      		=> 'editor-listen',
			'data-handler'		=> 'marquee',
			'style-class'		=> 'ce-dropzone ce-dropzone-no-unsplash gallery-upload ov-marquee-image',
		),
		'width' => array(
			'data-input-type' => 'select-box',
			'title'		 => 'Image Width',
			'size'		 => 'span2',
			'class'      	=> 'editor-listen',
			'data-handler' 	=> 'marquee',
			'data-target'=> '.is-content',
			'default' 	 => 'grid',
			'help'		 => '\'Original\' means that the image will not be scaled unless it is too big for the grid. If you choose \'Grid Width\', your image will always be scaled to match the grid width.',
			'style-class'	=> 'ov-marquee-image',
			'select-box-values' => array(
				'original'	 => 'Original',
				'custom' => 'Custom',
			),
		),
		'custom_width' => array(
			'title'			=> 'Custom Width (in %)',
			'size'			=> 'span2',
			'offset'		=> false,
			'data-input-type' 	=> 'range-slider',
			'default'		=> 100,
			'min'			=> 0,
			'max'			=> 100,
			'class'				=> 'editor-listen',
			'data-handler'		=> 'marquee',
			'data-range-slider' => 'marquee',
			'style-class'	=> 'ov-marquee-image',
			//'responsive'	=> true,
		),
		'margin_right' => array(
			'title'			=> 'Spacing (px)',
			'size'			=> 'span2',
			'offset'		=> false,
			'data-input-type' 	=> 'range-slider',
			'default'		=> 18,
			'min'			=> 0,
			'max'			=> 999,
			'class'				=> 'editor-listen',
			'data-handler'		=> 'marquee',
			'data-range-slider' => 'marquee',
			'data-has-unit'	=> true,
			'help' => 'Define your spacing for:<br /><br /><b>Text mode</b><br />The spacing will get added at the end of your text.<br /><br /><b>Image mode</b><br />Spacing will get added after each image.',
			//'responsive'	=> true,
		),
	),
	'title_formatting' => array(
		'title'  	 => 'Title Formatting',
		'break'		 => '2,2,2',
		'data-hide-mobile' => true,
		'style-class' => 'ep-collapsed ov-marquee-text',
		'color' => array(
			'title'				=> 'Color',
			'data-style-option' => true,
			'size'				=> 'span2',
			'data-input-type'	=> 'color',
			'default'			=> 'transparent',
			'class'				=> 'color-picker admin-listen-handler',
			'data-handler' 		=> 'colorPicker',
			'data-picker'		=> 'marquee'	
		),
		'font' => array(
			'data-input-type' => 'select-fonts',
			'title'		 		=> 'Font Family',
			'size'		 		=> 'span2',
			'class'				=> 'editor-listen',
			'data-handler'		=> 'marquee',
			'default' 	 		=> 'none',
			'select-box-values' => $atts->fonts,
		),
		'fontsize' => array(
			'title'			=> 'Font Size',
			'size'			=> 'span2',
			'offset'		=> false,
			'data-input-type' 	=> 'range-slider',
			'default'		=> 54,
			'min'			=> 0,
			'max'			=> 999,
			'class'				=> 'editor-listen',
			'data-handler'		=> 'marquee',
			'data-has-unit'	=> true,
			'data-range-slider' => 'marquee',
		),
		'lineheight' => array(
			'title'			=> 'Line Height',
			'size'			=> 'span2',
			'offset'		=> false,
			'data-input-type' 	=> 'range-slider',
			'default'		=> 72,
			'min'			=> 0,
			'max'			=> 999,
			'class'				=> 'editor-listen',
			'data-handler'		=> 'marquee',
			'data-has-unit'	=> true,
			'data-range-slider' => 'marquee',
		),
		'text_transform' => array(
			'title'				=> 'Text Transform',
			'size'				=> 'span2',
			'data-input-type'	=> 'select-box',
			'class'				=> 'editor-listen',
			'data-handler'		=> 'marquee',
			'default'			=> 'none',
			'select-box-values' => array(
				'none'			=> 'None',
				'uppercase'		=> 'Uppercase',
			),
		),
		'letter_spacing' => array(
			'title'			=> 'Letter Spacing',
			'size'			=> 'span2',
			'offset'		=> false,
			'data-input-type' 	=> 'range-slider',
			'default'		=> 0,
			'min'			=> 0,
			'max'			=> 9999,
			'class'			=> 'editor-listen',
			'data-handler'	=> 'marquee',
			'data-divider'  => 10,
			'data-has-unit'	=> true,
			'data-negative' => true,
			'data-range-slider' => 'marquee',
			'help'			=> 'This value increments the letter spacing in 0.1px steps. <br /><br /><b>Example:</b> 10 = 1px. <br /><br /><b>Note:</b><br />You will see the letter spacing also added to the last char on the right while editing. For the frontend this will get compensated with a negative margin to correctly align your button label.',
		),
	),
	// mobile marquee options
	'marquee_responsive_lg' => $atts->get_mobile('marquee', 'Desktop', 'lg', false),
	'marquee_responsive_md' => $atts->get_mobile('marquee', 'Tablet Landscape', 'md', false),
	'marquee_responsive_sm' => $atts->get_mobile('marquee', 'Tablet Portrait', 'sm', false),
	'marquee_responsive_xs' => $atts->get_mobile('marquee', 'Mobile', 'xs', false),
);

?>